[REF] Single Dockerfile and build scripts
* Deprecate 11.0
* Use a single Dockerfile
* Remove the old build.d directory
* Use build scripts to ease maintenance
* Move default configuration values to config-generate script
* Minimize tooling dependencies
* Rely on requirements specified by odoo
* Match python versions to those of runbot
* Remove support for CUSTOM_REPOSITORIES

diff --git a/entrypoint.d/600-wait-postgress b/entrypoint.d/600-wait-postgress
--- a/entrypoint.d/600-wait-postgress
+++ b/entrypoint.d/600-wait-postgress
@@ -1,19 +1,12 @@
 #!/bin/bash
 set -e
 
-# Know if Postgres is listening
-function db_is_listening() {
-    psql --list > /dev/null 2>&1 || (sleep 1 && db_is_listening)
-}
+if [ ${WAIT_PG:-true} == "true" ]; then
+    if [ -z "$PGHOST" ]; then
+        echo "ERROR: PGHOST is not defined" 1>&2
+        exit 1
+    fi
 
-# Check pg user exist
-function pg_user_exist() {
-    psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$PGUSER'" > /dev/null 2>&1 || (sleep 1 && pg_user_exist)
-}
-
-if [ "${WAIT_PG,,}" == "true" ]; then
-    echo Waiting until the database server is listening... > /dev/stderr
-    db_is_listening
-    echo Waiting until the pg user $PGUSER is created... > /dev/stderr
-    pg_user_exist
+    echo "Waiting for postgres to be ready..."
+    pg_isready --username $PGUSER --host $PGHOST
 fi
