[FIX] wait postgres: and add a configurable timeout

diff --git a/entrypoint.d/600-wait-postgress b/entrypoint.d/600-wait-postgress
--- a/entrypoint.d/600-wait-postgress
+++ b/entrypoint.d/600-wait-postgress
@@ -1,15 +1,34 @@
 #!/bin/bash
 set -e
 
-if [ ${WAIT_PG:-true} == "true" ]; then
-    if [ -z "$PGHOST" ]; then
-        echo "ERROR: PGHOST is not defined" 1>&2
-        exit 1
-    fi
-    if [ -z "$PGUSER" ]; then
-        echo "ERROR: PGUSER is not defined" 1>&2
-        exit 1
-    fi
-    echo "Waiting for postgres to be ready..."
-    pg_isready
+# Default value (set to 0 to disable)
+PG_WAIT_TIMEOUT=${PG_WAIT_TIMEOUT:-10}
+
+if [ ${PG_WAIT_TIMEOUT:-10} -le 0 ]; then
+    exit 0
 fi
+
+if [ -z "$PGHOST" ]; then
+    echo "ERROR: PGHOST is not defined" 1>&2
+    exit 1
+fi
+
+if [ -z "$PGUSER" ]; then
+    echo "ERROR: PGUSER is not defined" 1>&2
+    exit 1
+fi
+
+echo -n "Waiting for PostgreSQL to be ready ..."
+start_time=$(date +%s)
+until pg_isready -t 1 >/dev/null; do
+    current_time=$(date +%s)
+    elapsed_time=$((current_time - start_time))
+    if [ "$elapsed_time" -ge "$PG_WAIT_TIMEOUT" ]; then
+        echo "."
+        echo "Unable to reach PostgreSQL server" 1>&2
+        exit 1
+    fi
+    echo -n "."
+done
+
+echo " [OK]"
